sonar.serverUrl=http://localhost:9000
sonar.token=sqp_a38036d6ae0fa911d1ee6260b7ae850f051f2921

sonar.projectKey=Evangalicapp
sonar.projectName=EvangalicApp

sonar.sources=src
sonar.exclusions=**/node_modules/**, **/.next/**, **/dist/**, **/*.spec.ts, **/*.test.ts
sonar.sourceEncoding=UTF-8